name: tedarik
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  image_picker: ^1.0.7
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.PNG
