// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgi3aX3oCgzj7TkGAlvUTh61eS5gNqWxI',
    appId: '1:136111455235:web:55a82a3621a113bf3ce236',
    messagingSenderId: '136111455235',
    projectId: 'tedarik-1e527',
    authDomain: 'tedarik-1e527.firebaseapp.com',
    storageBucket: 'tedarik-1e527.appspot.com',
    measurementId: 'G-Y853RZLTZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWK8OqxtGfKUgtA4QW6obbtpVSlGGEZ_I',
    appId: '1:136111455235:android:d3afb0d431d90dbb3ce236',
    messagingSenderId: '136111455235',
    projectId: 'tedarik-1e527',
    storageBucket: 'tedarik-1e527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuCyXKJBbdbgwKl7ASU4UEhe-uzX8WBJc',
    appId: '1:136111455235:ios:c08be5c30bef6d213ce236',
    messagingSenderId: '136111455235',
    projectId: 'tedarik-1e527',
    storageBucket: 'tedarik-1e527.appspot.com',
    iosBundleId: 'com.mobilfinal.tedarik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuCyXKJBbdbgwKl7ASU4UEhe-uzX8WBJc',
    appId: '1:136111455235:ios:e7030d4a6cb2d56b3ce236',
    messagingSenderId: '136111455235',
    projectId: 'tedarik-1e527',
    storageBucket: 'tedarik-1e527.appspot.com',
    iosBundleId: 'com.mobilfinal.tedarik.RunnerTests',
  );
}
